version: "3.9"
services:
  ganache-cli:
    build:
      context: ganache
      args:
        GANACHE_MNEMONIC: $GANACHE_MNEMONIC
    ports:
      - 8545:8545
    volumes:
      - ./ganache/db:/db
  contracts:
    build: contracts
    volumes:
      - ./contracts:/code
    stdin_open: true
    tty: true
  backend:
    build: backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
      
